# Generated by Django 5.1.7 on 2025-03-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='customer_phone',
        ),
    ]
